name: Create Dungeon Tuber Windows 

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update version with current tag reference
      id: vars
      run: |        
        $version = $env:GITHUB_REF_NAME.TrimStart("v")
        $version | Set-Content -Encoding ASCII version.txt
        (Get-Content version.rc) -replace "'ProductVersion', '(.*?)'", ("'ProductVersion', '" + $version + "'") | Out-File -encoding UTF8noBom version.rc
        (Get-Content pyproject.toml) -replace 'version = "(.*?)"', ('version = "' + $version + '"') | Out-File -encoding UTF8noBom pyproject.toml
        echo "app_version=$version" >> $env:GITHUB_OUTPUT

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install .[dev]

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Create Nuitka Executable
      if: false
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: DungeonTuber.py
        mode: app
        low-memory: true
        output-dir: build
        jobs: 1
        enable-plugins: pyside6

    - name: Create Pyinstaller Executable
      run: |        
        pyinstaller DungeonTuber.spec

    - name: Compile .ISS to .EXE Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
      with:
        path: DungeonTuber.iss
        options: /O+

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: DungeonTuber-*.exe
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.vars.outputs.app_version }}
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DungeonTuber-${{ steps.vars.outputs.app_version }}
        path: DungeonTuber-*.exe